// src/domain/entities/Beneficiary.ts

interface Address {
    street: string;
    city: string;
    state: string;
    zipCode: string;
    country: string;
}

interface FamilyDetails {
    membersCount: string;
    incomeLevel: string;
}

export interface Beneficiary {
    id?: string; // Optional ID, could be generated by database
    details: string;
    condition: string;
    dateOfBirth: string;
    gender: string;
    identificationType: string;
    identificationNumber: string;
    address: Address;
    familyDetails: FamilyDetails;
    uploadedFiles: string[]; // Store file paths or URLs as strings
    createdAt?: Date;
    updatedAt?: Date;
}